# Generated by Django 5.1.1 on 2025-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinksdata', '0002_alter_drinks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
